### ISSUE TITLE
Oberon0 to FORTH for the Propeller2 ?

### ISSUE THREAD

**Issue by MGreim** [lboasso/oberon0#1]
Hi, 

I have seen your Oberon0 and Oberon7 compile for the Java-VM. 
I am playing around with Oberon from time to time. 
For example, I have translated the de Wachters RISC-V emulator to Pascal and Ultibo and
also realized the Project Oberon on the Spartan board. 
But I have to say I am not a compiler specialist. 
My idea is actually to modify the  Oberon-0 compiler for FORTH instead the Java-VM. 
Specially for TAQOZ which is the built in FORTH for the Propeller-2 processor of Parallax Inc. 

At the end of the day,  as a first basic buidling block for Project Oberon on the Propeller-2. 
Do you think it make sense to modify your project? 
Or are the Java-VLM and FORTH so different, that it is better to start from the scratch?

Any comment wellcome. 

Regards

Markus Greim, Germany

[Link to TAQOZ](https://sourceforge.net/projects/tachyon-forth/files/TAQOZ/)
[Link to the Propeller 2](https://www.parallax.com/propeller-2/)

**Comment by lboasso** [comment]
Hi Markus, 

Thanks for your interest in Oberon!
If you want to port the Oberon-07 compiler, I agree it is best to start with the Oberon-0 language/compiler first. 
The code in this repository targets Wirth's own RISC architecture, but it is a good starting point since it is small and documented in his [book](https://people.inf.ethz.ch/wirth/CompilerConstruction/index.html). [oberonc](https://github.com/lboasso/oberonc) targets the JVM and supports the full Oberon-07 language so it might not be the best place to start.
Targeting a stack machine / intermediate language like FORTH could be simpler but why don't you target directly the [PASM Instructions set](https://docs.google.com/spreadsheets/d/1_vJk-Ad569UMwgXTKTdfJkHYHpc1rZwxB-DcIiAZNdk/edit#gid=0)?

Cheers, 
Luca

**Comment by MGreim** [comment]
Hi Luca, 
thanks for your answer. 

> Targeting a stack machine / intermediate language like FORTH could be simpler but why don't you target directly the PASM Instructions set?


Good question: I have to say my "feeling" was, that the using FORTH as intermediate step would make things simpler. 
But maybe that is wrong and  FORTH will make things much more complicated. 
Highest speed and optimization is not my first aim. I want try to keep things as simple as possible as Wirth says.
Whats your opinion?

Best Regards
from the snowy Bavaria

Markus

**Comment by lboasso** [comment]
If you are familiar with PASM assembly and you can write small programs in it, I would suggest to target that directly.
I will be happy to help you in this project, I can publish an oberon0 compiler I wrote years ago, that targets a much simpler stack machine than the JVM. That code could help you in targetting FORTH.
Let's continue this conversation by email: luke.boasso@gmail.com
